Ignore NoClassDefFoundError when loading custom audit log plugins (#2556) (#2563)
Before 1.19, the custom plugin class needed to implement the org.apache.doris.plugin.AuditPlugin interface. AuditPlugin has been renamed to com.starrocks.AuditPlugin after 1.19, so NoClassDefFoundError will be thrown when loading the custom plugin class. In order to prioritize the cluster to work properly, we should ignore NoClassDefFoundError when loading custom audit log plugins.